import FlaskIcon from "../components/shared/icons/FlaskIcon";

const projectData = [
  {
    logo: <FlaskIcon />,
    name: "Stand Alone Customer Service Kiosk",
    description:
      "Speech to Text, Text to AI, AI to Text, Text to Voice.  We delivered a powerful conversational AI solution that runs on local hardware and is trained on private data. This system ensures a seamless and intuitive user experience through both voice and touch interactions.",
    tagLine: "",
    tagLineDescription: "Technologies Involved: .NET MAUI, Text-to-Speech, Speech-to-Text, Peripheral hardware integration, Local LLM Hosting (using Ollama), and AI models like LLaMA3 GPT-8B.",
    link: "",
  },
  {
    logo: <FlaskIcon />,
    name: "Dynamic LLM Interaction Large Documents",
    description:
      "Making Complex Information Accessible.  We developed a custom prompting service that enables chatbot interactions, both text and voice, with large documents and diverse data sources. This service provides an engaging user experience, making complex and extensive information easily accessible.",
    tagLine: "",
    tagLineDescription: "Technologies Involved: .NET MAUI, Document Consumer and Indexer, PDF Markup, Multi-Sourced Prompting, Embeddings, Vectorized Data, Local LLM Hosting (using Ollama), and AI models like LLaMA3 GPT.",
    link: "",
  },
  {
    logo: <FlaskIcon />,
    name: "TMRA - The Most Ridiculous Adventure",
    description:
      "AI & Player Interactive Story Builder. We created TMRA, the world's first interactive story builder combining AI and player input. Players provide details about their story, characters, and goals, and our AI generates a backstory, current scene, and next steps. This guided experience offers a unique, co-narrated adventure, enhanced by images generated by StableDiffusion to match the narrative.",
    tagLine: "",
    tagLineDescription: "Technologies Involved: Blazor WebAssembly, MSSQL, OpenAI GPT-3.5 Turbo, and StableDiffusion on a private host",
    link: "",
  },
  // {
  //   logo: <FlaskIcon />,
  //   name: "Stand Alone Customer Service Kiosk",
  //   description:
  //     "We designed and developed a stand-alone customer service kiosk with advanced voice and AI capabilities. The kiosk includes voice-to-text, text-to-local AI, local AI-to-text, and text-to-voice functionalities. It also features on-screen navigation display, lidar for user and height detection, and supports various printer integrations for stickers, receipts, and cardstock. Additionally, it supports custom voices and multiple languages for text-to-speech and spoken interactions.",
  //   tagLine: "65.25%",
  //   tagLineDescription: "Increase time to prototype",
  //   link: "",
  // },
  {
    logo: <FlaskIcon />,
    name: "AI-Driven Recommendation System",
    description:
      "Personalized Recommendations for Any Topic.  We developed an AI-driven recommendation system that accepts any topic, builds a profile to compare items, and evaluates three of the user's favorite instances. Based on the user's preferences, the system suggests additional recommendations and provides insights into what the user enjoys most about their original choices.",
      tagLine: "",
      tagLineDescription: "Technologies Involved: Blazor WebAssembly, OpenAI GPT-3.5 Turbo, and StableDiffusion on a private host.",
    link: "",
  },
  {
    logo: <FlaskIcon />,
    name: "LiveVotingApp - Real-time Crowd Interaction Software",
    description: "Seamless Real-time Audience Engagement. We developed LiveVotingApp, a real-time crowd interaction software that connects hundreds of thousands of devices seamlessly. Using SignalR, this solution enables live audience interactions, voting, and more, delivering an engaging experience for users.",
    tagLine: "",
    tagLineDescription: "Technologies Involved: Blazor WebAssembly, MSSQL, SignalR, Clean Architecture, Automated Testing, Jenkins Build Pipeline, Nginx Reverse Proxy, and Docker Containers.",
    link: "",
  },
  {
    logo: <FlaskIcon />,
    name: "Security Scanning Application",
    description: "Comprehensive Network Security in a Box.  In collaboration with a client, we co-developed a security scanning application that integrates multiple APIs to provide extensive network security services. This application performs regular checkups on corporate networks, dark web files, business domains, and employee email addresses to ensure maximum safety and security.",
    tagLine: "",
    tagLineDescription: "Technologies Involved: Blazor WebAssembly, MSSQL, Multi-Tenancy, Automated State Machine, Clean Architecture, Automated Testing, Jenkins Build Pipeline, Nginx Reverse Proxy, and Docker Containers.",
    link: "",
  },
  {
    logo: <FlaskIcon />,
    name: "Online Referral and Vendor Backend System",
    description: "Boosting Engagement and Generating Leads. We developed an online referral and vendor backend system that enables peer vendors to offer site visitors direct email referral opportunities. This system enhances user engagement and provides vendors with valuable leads, driving increased sales and revenue.",
    tagLine: "",
    tagLineDescription: "Technologies Involved: Blazor WebAssembly, MSSQL, Multi-Tennancy, Clean Architecture, Automated Testing, Jenkins Build Pipeline, Nginx Reverse Proxy, and Docker Containers",
    link: "",
  },
  {
    logo: <FlaskIcon />,
    name: "Automation Application",
    description: "Streamlining Office Workflows. We developed an automation application that leverages an elaborate state machine to handle routine office tasks, automating 80% of the staff's workload. By automating tasks such as reading, sending, and processing emails, we enabled front-line workers to focus on the most critical and unique cases.",
    tagLine: "",
    tagLineDescription: "Technologies Involved: Angular, .NET APIs, MSSQL, Identity Server, AD SAML2 SSO, Stateless.",
    link: "",
  },







  // {
  //   logo: <FlaskIcon />,
  //   name: "Large Scale Energy Management",
  //   description: "",
  //   tagLine: "",
  //   tagLineDescription: "Technologies Involved: Angular, .NET APIs, MSSQL, Identity Server, AD SAML2 SSO, Stateless.",
  //   link: "",
  // },
  // {
  //   logo: <FlaskIcon />,
  //   name: "International Association Custom Operations Solution",
  //   description: "",
  //   tagLine: "",
  //   tagLineDescription: "Technologies Involved: Angular, .NET APIs, MSSQL, Identity Server, AD SAML2 SSO, Stateless.",
  //   link: "",
  // },
  // {
  //   logo: <FlaskIcon />,
  //   name: "Automation Application",
  //   description: "",
  //   tagLine: "",
  //   tagLineDescription: "Technologies Involved: Angular, .NET APIs, MSSQL, Identity Server, AD SAML2 SSO, Stateless.",
  //   link: "",
  // },
  // {
  //   logo: <FlaskIcon />,
  //   name: "Automation Application",
  //   description: "",
  //   tagLine: "",
  //   tagLineDescription: "Technologies Involved: Angular, .NET APIs, MSSQL, Identity Server, AD SAML2 SSO, Stateless.",
  //   link: "",
  // },
  // {
  //   logo: <FlaskIcon />,
  //   name: "Automation Application",
  //   description: "",
  //   tagLine: "",
  //   tagLineDescription: "Technologies Involved: Angular, .NET APIs, MSSQL, Identity Server, AD SAML2 SSO, Stateless.",
  //   link: "",
  // },
  // {
  //   logo: <FlaskIcon />,
  //   name: "Meet Our Kit",
  //   description: "",
  //   tagLine: "",
  //   tagLineDescription: "Technologies Involved: Angular, .NET APIs, MSSQL, Identity Server, AD SAML2 SSO, Stateless.",
  //   link: "",
  // }
  // {
  //   logo: <FlaskIcon />,
  //   name: "",
  //   description: "",
  //   tagLine: "65.25%",
  //   tagLineDescription: "Increase time to prototype",
  //   link: "",
  // },
];

export default projectData;